# Attendance Exercise 03

In [3]:
import numpy as np 
import pandas as pd

## 1. Introduction to the pandas package

In [4]:
# this is the dicionaty which you will need to complete the tasks of this exercise. DO NOT REMOVE IT
exam_data_dict  = {'name': ['Niklas', 'Moritz', 'Emily', 'Samantha', 'Katrin', 'Julien', 'Laura', 'Leila', 'Peter', 'John'],
    'score': [np.nan, 3, 13.5, 7, 5, 19, 13.5, np.nan, 9, 14],
    'attempts': [3, 1, 2, 3, 2, 3, 1, 2, 2, 1],
    'qualify': ['no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes']}

### 1.a) DataFrame creation

In [9]:
df= pd.DataFrame(exam_data_dict)
df.info()
df.head()
df.tail()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
name        10 non-null object
score       8 non-null float64
attempts    10 non-null int64
qualify     10 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


score   attempts
count   8.000000  10.000000
mean   10.500000   2.000000
std     5.391793   0.816497
min     3.000000   1.000000
25%     6.500000   1.250000
50%    11.250000   2.000000
75%    13.625000   2.750000
max    19.000000   3.000000

### 1.b) Loading / saving of DataFrames

In [10]:
df.to_csv("students_exam.csv")

In [12]:
df2 = pd.read_csv("students_exam.csv")
df2.tail()

Unnamed: 0   name  score  attempts qualify
6            6  Laura   13.5         1     yes
7            7  Leila    NaN         2     yes
8            8  Peter    9.0         2     yes
9            9   John   14.0         1     yes
10           9  JMohn   12.0         2      no

### 1.c) Data selection

In [16]:
print(df2.columns)
df3 = df2[["name","score"]]
df3.head()

Index(['Unnamed: 0', 'name', 'score', 'attempts', 'qualify'], dtype='object')


name  score
0    Niklas    NaN
1    Moritz    3.0
2     Emily   13.5
3  Samantha    7.0
4    Katrin    5.0

### 1.d) Ill-defnied values

In [18]:
df3.replace(np.nan, 0)

name  score
0     Niklas    0.0
1     Moritz    3.0
2      Emily   13.5
3   Samantha    7.0
4     Katrin    5.0
5     Julien   19.0
6      Laura   13.5
7      Leila    0.0
8      Peter    9.0
9       John   14.0
10     JMohn   12.0

### 1.e) Passing students

In [55]:
l1= df3.loc[df3["score"]>=10].values.tolist()
l1.sort(key = lambda n : n[1], reverse = True)
l1

[['Julien', 19.0],
 ['John', 14.0],
 ['Emily', 13.5],
 ['Laura', 13.5],
 ['JMohn', 12.0]]

## 2. Introduction to the NumPy package

In [56]:
# these are the two list which you will need to complete the tasks of this exercise. DO NOT REMOVE THEM
list_1D = [7, 5, 9, 0, 3, 1 ,4]
list_2D = [[1, 0, 2], [3, 1, 2], [0, 1, 1]]

### 1.a) NumPy array creation

In [61]:
n_arr = []
n_arr.append(np.array(list_1D))
n_arr.append(np.array(list_2D))
n_arr.append(np.linspace(1,10,10))
n_arr.append(np.zeros(5))
n_arr.append(np.ones(5))
for n in n_arr:
    print(n)

[7 5 9 0 3 1 4]
[[1 0 2]
 [3 1 2]
 [0 1 1]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


### 1.b) Array shapes and dimensions

In [63]:
i= 0
for n in n_arr:
    print(i)
    print(n.shape)
    print(n.ndim)
    print()
    i+=1

0
(7,)
1

1
(3, 3)
2

2
(10,)
1

3
(5,)
1

4
(5,)
1



### 1.c) Copying of arrays

In [64]:
using_1 = n_arr[1]
using_2 = np.copy(n_arr[1])
using_1[1,1]= 15
print(using_1)
print(using_2)

[[ 1  0  2]
 [ 3 15  2]
 [ 0  1  1]]
[[1 0 2]
 [3 1 2]
 [0 1 1]]


### 1.d) Insert/delete

In [78]:
print(np.insert(n_arr[1], 1, [1,1,1], axis= 1))
print(np.delete(n_arr[1], 1, axis= 0))

[[ 1  1  0  2]
 [ 3  1 15  2]
 [ 0  1  1  1]]
[[1 0 2]
 [0 1 1]]


### 1.e) Array combination

In [ ]:
pass

### 1.f) Array math

In [ ]:
pass

### 1.g) Matrix inverse

### 1.h) Statistics with NumPy