In [1]:
import pandas as pd
import numpy as np

import tensorflow.keras
from tensorflow.keras import Sequential as Sequential
import tensorflow.keras.layers as layers

D:\Programme\Python3_8_MiniConda\envs\physics718\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Programme\Python3_8_MiniConda\envs\physics718\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Programme\Python3_8_MiniConda\envs\physics718\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Programme\Python3_8_MiniConda\e

## Loading dataset

In [6]:
df = pd.read_csv('train.csv')
df.head()
cols_n = df.columns.values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   LifeTime             10001 non-null  float64
 1   FlightDistance       10001 non-null  float64
 2   FlightDistanceError  10001 non-null  float64
 3   IP                   10001 non-null  float64
 4   VertexChi2           10001 non-null  float64
 5   pt                   10001 non-null  float64
 6   DOCAone              10001 non-null  float64
 7   DOCAtwo              10001 non-null  float64
 8   DOCAthree            10001 non-null  float64
 9   IP_p0p2              10001 non-null  float64
 10  IP_p1p2              10001 non-null  float64
 11  isolationa           10001 non-null  int64  
 12  isolationb           10001 non-null  int64  
 13  isolationc           10001 non-null  int64  
 14  CDF1                 10001 non-null  float64
 15  CDF2                 10001 non-null 

## Transforming features

In [3]:
from sklearn.preprocessing import QuantileTransformer

cols = df.columns[:-1]

Xraw = df[cols].to_numpy()
Y = df['signal'].to_numpy()

print(Xraw)
print(Xraw.shape)

X = QuantileTransformer().fit_transform(Xraw)

print(X)

[[9.85366176e-04 1.00298471e+01 3.43366027e-01 ... 3.16042209e+00
  2.75811648e+00 2.76095486e+00]
 [5.33150509e-04 1.15073938e+01 7.00662017e-01 ... 3.49505711e+00
  4.08623981e+00 3.45623326e+00]
 [2.46602017e-03 1.64100037e+01 4.04927462e-01 ... 3.76575851e+00
  3.17969036e+00 2.85043478e+00]
 ...
 [5.85318252e-04 5.30118752e+00 3.27816844e-01 ... 3.50842810e+00
  2.81191301e+00 3.37027335e+00]
 [4.67951875e-04 1.03652992e+01 1.15061641e+00 ... 3.57180691e+00
  4.27784300e+00 3.86763835e+00]
 [2.71984539e-03 1.64097157e+01 1.72801018e-01 ... 2.31482935e+00
  2.33921742e+00 2.10752225e+00]]
(10001, 32)
[[0.44172596 0.47009413 0.4697109  ... 0.45002673 0.25587871 0.2353541 ]
 [0.10445369 0.53797549 0.8101436  ... 0.65268083 0.92109174 0.64730934]
 [0.93190534 0.70271303 0.56865668 ... 0.78744371 0.50860115 0.28508633]
 ...
 [0.14077948 0.18768081 0.44066123 ... 0.66025846 0.28789067 0.60057343]
 [0.065856   0.48573559 0.92727915 ... 0.69296045 0.96121596 0.84334694]
 [0.95215982 0.702

## Splitting into training and testing data

In [4]:
from sklearn.model_selection import train_test_split

Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size=0.2)

In [5]:
# this function calculates a simple score to evaluate the performance of your neural network
def SimpleScore(model, xtest, ytest):
    pred = model.predict(xtest)

    if (pred.shape != ytest.shape): # important! prevents broadcasting
        pred=pred.reshape(ytest.shape) 

    diff = np.abs(pred - np.clip(ytest,0,1))
    
    return np.mean(np.less(diff,0.5))  

## Implementing neural network with two hidden layers

## Implementing neural network with four hidden layers